version: '3'

services: 

  # Start POSTGRES, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vueapi
    volumes:
      - ./db-data/postgres/:/var/lib/postgressql/data/

  # Start mailing
  mailhog:
    image: 'mailhog/mailhog:latest'
    platform: linux/amd64
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always